support for laravel 7
michaeldyrynda/laravel-preset-tailwind pull request #88
Opened 2020-03-04 14:00 UTC by yaelahan

proof: ![Screenshot_20200304_205531](https://user-images.githubusercontent.com/35204891/75886489-de6d6400-5e5a-11ea-8931-a1731629ecaf.jpg)

2020-03-04 14:52 UTC, yaelahan commented
for testing add this line into **composer.json** on your laravel project
```
...

"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/yaelahan/tailwindcss"
    }
],
...
```

and then run 

> composer require laravel-frontend-presets/tailwindcss:dev-alternate-universe --dev
> php artisan ui tailwindcss-auth
> npm install && npm run dev
> php artisan serve

2020-03-04 21:15 UTC, perezale commented
Worked for me!
Tried with php artisan ui tailwindcss (no auth)

2020-03-04 21:25 UTC, sjardim commented
Confirm it's working with Auth as well. Thank you!

2020-03-05 00:30 UTC, mathieutu requested changes
Hi, 
The auth scaffolding is now done by the ui:auth command (or ui --auth).

As you can see in the follwing lines, we can add a type by adding a macro to the AuthCommand:

https://github.com/laravel/ui/blob/948bd6ad08467b8e9cd03cd2af8d86a3a330bbc0/src/AuthCommand.php#L52-L54

I've made the modifications in suggestions.

2020-03-05 00:30 UTC, mathieutu commented on src/TailwindCssPresetServiceProvider.php
> +        UiCommand::macro('tailwindcss-auth', function ($command) {
```suggestion
        AuthCommand::macro('tailwindcss', function ($command) {
```

2020-03-05 00:30 UTC, mathieutu commented on src/TailwindCssPresetServiceProvider.php
> +use Laravel\Ui\UiCommand;
```suggestion
use Laravel\Ui\UiCommand;
use Laravel\Ui\AuthCommand;
```

2020-03-05 00:59 UTC, yaelahan commented on src/TailwindCssPresetServiceProvider.php
> +        UiCommand::macro('tailwindcss-auth', function ($command) {
nice one. thank you for reviewing

2020-03-05 09:19 UTC, mathieutu commented on src/TailwindCssPreset.php
> -    protected static function updatePagination()
So we remove the tailwind pagination? Why? 🤔

2020-03-05 20:01 UTC, merged

2020-03-05 20:02 UTC, michaeldyrynda commented
I restored the pagination functionality and tagged as 4.0.0. Thanks!